/** DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "org_ice1000_public_functions.h"
/** Header for class org_ice1000_util_Math */

#ifndef _Included_org_ice1000_util_Math
#define _Included_org_ice1000_util_Math

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

#undef org_ice1000_util_Math_E
#define org_ice1000_util_Math_E 2.718281828459045

#undef org_ice1000_util_Math_PI
#define org_ice1000_util_Math_PI 3.141592653589793

/// 0x5F3759DF thank you Carmack
#undef org_ice1000_util_Math_MAGIC_NUMBER
#define org_ice1000_util_Math_MAGIC_NUMBER 1597463007L

/**
 * Class:     org_ice1000_util_Math
 * Method:    gcd
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ice1000_util_Math_gcd(
	JNIEnv *,
	jclass,
	jlong,
	jlong
);

/**
 * Class:     org_ice1000_util_Math
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_ice1000_util_Math_sqrt(
	JNIEnv *,
	jclass,
	jdouble
);

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_ice1000_util_Math
