/* DO NOT EDIT THIS FILE - it is machine generated */
#include "org_ice1000_public_functions.h"
/* Header for class org_ice1000_util_Arrays */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_ice1000_util_ArrayUtils
#define _Included_org_ice1000_util_ArrayUtils

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    discretization
 * Signature: ([JI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_discretization___3JI( 
		JNIEnv *,
		jclass,
		jlongArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    discretization
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_discretization___3II( 
		JNIEnv *,
		jclass,
		jintArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    discretization
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_discretization___3DI( 
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    discretization
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_discretization___3FI( 
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    discretization
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_discretization___3SI( 
		JNIEnv *,
		jclass,
		jshortArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    quickSort
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_quickSort___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    quickSort
 * Signature: ([JI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_quickSort___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    quickSort
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_quickSort___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    quickSort
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_quickSort___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    quickSort
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_quickSort___3SI(
		JNIEnv *,
		jclass,
		jshortArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    quickSort
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_quickSort___3BI(
		JNIEnv *,
		jclass,
		jbyteArray,
		jint
);

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_ice1000_util_ArrayUtils



#pragma clang diagnostic pop