/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
/* Header for class org_ice1000_graph_FrontStarGraph */

#ifndef _Included_org_ice1000_graph_FrontStarGraph
#define _Included_org_ice1000_graph_FrontStarGraph

#ifndef __ice_memset
#define __ice_memset(x, y) (memset(x, y, sizeof(x)))
#endif /// __ice_memset

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     org_ice1000_graph_FrontStarGraph
 * Method:    spfa
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ice1000_graph_FrontStarGraph_spfa(
		JNIEnv *,
		jobject,
		jint,
		jlongArray,
		jlongArray,
		jlongArray,
		jlongArray,
		jint,
		jint
);

/**
 * Class:     org_ice1000_graph_FrontStarGraph
 * Method:    kruskal
 * Signature: ([J[J[J[JII)J
 */
JNIEXPORT jlong JNICALL Java_org_ice1000_graph_FrontStarGraph_kruskal(
		JNIEnv *,
		jobject,
		jlongArray,
		jlongArray,
		jlongArray,
		jlongArray,
		jint,
		jint
);


/**
 * Class:     org_ice1000_graph_FrontStarGraph
 * Method:    init
 * Signature: ([J[J[J[JII)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_graph_FrontStarGraph_init(
		JNIEnv *,
		jobject,
		jlongArray,
		jlongArray,
		jlongArray,
		jlongArray,
		jint,
		jint
);

#ifdef __cplusplus
}
#endif
#endif
