/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "org_ice1000_public_functions.h"
/* Header for class org_ice1000_util_Arrays */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_ice1000_util_ArrayUtils
#define _Included_org_ice1000_util_ArrayUtils

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     org_ice1000_util_Arrays
 * Method:    discretization
 * Signature: ([JI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_discretization( 
		JNIEnv *,
		jobject,
		jlongArray,
		jint
);

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_ice1000_util_ArrayUtils

#pragma clang diagnostic pop

