/* DO NOT EDIT THIS FILE - it is machine generated */
#include "org_ice1000_public_functions.h"
/* Header for class org_ice1000_util_Arrays */

#ifndef _Included_org_ice1000_util_ArrayUtils
#define _Included_org_ice1000_util_ArrayUtils

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    discretization
 * Signature: ([JI)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_discretization___3JI( 
		JNIEnv *,
		jclass,
		jlongArray,
		jint
);

/**
 * Class:     org_ice1000_util_ArrayUtils
 * Method:    discretization
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_org_ice1000_util_ArrayUtils_discretization___3II( 
		JNIEnv *,
		jclass,
		jintArray,
		jint
);

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_ice1000_util_ArrayUtils


