///
/// Created by ice1000
///

/** DO NOT EDIT THIS FILE - it is machine generated */
#include "org_ice1000_public_functions.h"
/** Header for class org_ice1000_bit_BinaryIndexedTree */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_ice1000_bit_BinaryIndexedTree
#define _Included_org_ice1000_bit_BinaryIndexedTree

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_ice1000_bit_BinaryIndexedTree
 * Method:    add
 * Signature: ([JIIJ)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_bit_BinaryIndexedTree_add(
		JNIEnv *,
		jobject,
		jlongArray,
		jint,
		jint,
		jlong
) -> void;

/**
 * Class:     org_ice1000_bit_BinaryIndexedTree
 * Method:    sum
 * Signature: ([JII)J
 */
JNIEXPORT auto JNICALL Java_org_ice1000_bit_BinaryIndexedTree_sum(
		JNIEnv *,
		jobject,
		jlongArray,
		jint,
		jint
) -> jlong;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_ice1000_bit_BinaryIndexedTree


#pragma clang diagnostic pop
