# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Program Files (x86)\JetBrains\CLion 2017.1\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Program Files (x86)\JetBrains\CLion 2017.1\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\git-repos\algo4j\jni

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\git-repos\algo4j

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"D:\Program Files (x86)\JetBrains\CLion 2017.1\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"D:\Program Files (x86)\JetBrains\CLion 2017.1\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\git-repos\algo4j\CMakeFiles D:\git-repos\algo4j\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\git-repos\algo4j\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jni

# Build rule for target.
jni: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 jni
.PHONY : jni

# fast build rule for target.
jni/fast:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/build
.PHONY : jni/fast

global/bigint.obj: global/bigint.cpp.obj

.PHONY : global/bigint.obj

# target to build an object file
global/bigint.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/bigint.cpp.obj
.PHONY : global/bigint.cpp.obj

global/bigint.i: global/bigint.cpp.i

.PHONY : global/bigint.i

# target to preprocess a source file
global/bigint.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/bigint.cpp.i
.PHONY : global/bigint.cpp.i

global/bigint.s: global/bigint.cpp.s

.PHONY : global/bigint.s

# target to generate assembly for a file
global/bigint.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/bigint.cpp.s
.PHONY : global/bigint.cpp.s

global/functions.obj: global/functions.cpp.obj

.PHONY : global/functions.obj

# target to build an object file
global/functions.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/functions.cpp.obj
.PHONY : global/functions.cpp.obj

global/functions.i: global/functions.cpp.i

.PHONY : global/functions.i

# target to preprocess a source file
global/functions.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/functions.cpp.i
.PHONY : global/functions.cpp.i

global/functions.s: global/functions.cpp.s

.PHONY : global/functions.s

# target to generate assembly for a file
global/functions.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/functions.cpp.s
.PHONY : global/functions.cpp.s

global/matrix.obj: global/matrix.cpp.obj

.PHONY : global/matrix.obj

# target to build an object file
global/matrix.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/matrix.cpp.obj
.PHONY : global/matrix.cpp.obj

global/matrix.i: global/matrix.cpp.i

.PHONY : global/matrix.i

# target to preprocess a source file
global/matrix.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/matrix.cpp.i
.PHONY : global/matrix.cpp.i

global/matrix.s: global/matrix.cpp.s

.PHONY : global/matrix.s

# target to generate assembly for a file
global/matrix.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/matrix.cpp.s
.PHONY : global/matrix.cpp.s

global/trie.obj: global/trie.cpp.obj

.PHONY : global/trie.obj

# target to build an object file
global/trie.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/trie.cpp.obj
.PHONY : global/trie.cpp.obj

global/trie.i: global/trie.cpp.i

.PHONY : global/trie.i

# target to preprocess a source file
global/trie.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/trie.cpp.i
.PHONY : global/trie.cpp.i

global/trie.s: global/trie.cpp.s

.PHONY : global/trie.s

# target to generate assembly for a file
global/trie.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/global/trie.cpp.s
.PHONY : global/trie.cpp.s

graph/AdjacentMatrixGraph.obj: graph/AdjacentMatrixGraph.cpp.obj

.PHONY : graph/AdjacentMatrixGraph.obj

# target to build an object file
graph/AdjacentMatrixGraph.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/graph/AdjacentMatrixGraph.cpp.obj
.PHONY : graph/AdjacentMatrixGraph.cpp.obj

graph/AdjacentMatrixGraph.i: graph/AdjacentMatrixGraph.cpp.i

.PHONY : graph/AdjacentMatrixGraph.i

# target to preprocess a source file
graph/AdjacentMatrixGraph.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/graph/AdjacentMatrixGraph.cpp.i
.PHONY : graph/AdjacentMatrixGraph.cpp.i

graph/AdjacentMatrixGraph.s: graph/AdjacentMatrixGraph.cpp.s

.PHONY : graph/AdjacentMatrixGraph.s

# target to generate assembly for a file
graph/AdjacentMatrixGraph.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/graph/AdjacentMatrixGraph.cpp.s
.PHONY : graph/AdjacentMatrixGraph.cpp.s

graph/FrontStarGraph.obj: graph/FrontStarGraph.cpp.obj

.PHONY : graph/FrontStarGraph.obj

# target to build an object file
graph/FrontStarGraph.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/graph/FrontStarGraph.cpp.obj
.PHONY : graph/FrontStarGraph.cpp.obj

graph/FrontStarGraph.i: graph/FrontStarGraph.cpp.i

.PHONY : graph/FrontStarGraph.i

# target to preprocess a source file
graph/FrontStarGraph.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/graph/FrontStarGraph.cpp.i
.PHONY : graph/FrontStarGraph.cpp.i

graph/FrontStarGraph.s: graph/FrontStarGraph.cpp.s

.PHONY : graph/FrontStarGraph.s

# target to generate assembly for a file
graph/FrontStarGraph.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/graph/FrontStarGraph.cpp.s
.PHONY : graph/FrontStarGraph.cpp.s

math/BigInt.obj: math/BigInt.cpp.obj

.PHONY : math/BigInt.obj

# target to build an object file
math/BigInt.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/BigInt.cpp.obj
.PHONY : math/BigInt.cpp.obj

math/BigInt.i: math/BigInt.cpp.i

.PHONY : math/BigInt.i

# target to preprocess a source file
math/BigInt.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/BigInt.cpp.i
.PHONY : math/BigInt.cpp.i

math/BigInt.s: math/BigInt.cpp.s

.PHONY : math/BigInt.s

# target to generate assembly for a file
math/BigInt.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/BigInt.cpp.s
.PHONY : math/BigInt.cpp.s

math/MathUtils.obj: math/MathUtils.cpp.obj

.PHONY : math/MathUtils.obj

# target to build an object file
math/MathUtils.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/MathUtils.cpp.obj
.PHONY : math/MathUtils.cpp.obj

math/MathUtils.i: math/MathUtils.cpp.i

.PHONY : math/MathUtils.i

# target to preprocess a source file
math/MathUtils.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/MathUtils.cpp.i
.PHONY : math/MathUtils.cpp.i

math/MathUtils.s: math/MathUtils.cpp.s

.PHONY : math/MathUtils.s

# target to generate assembly for a file
math/MathUtils.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/MathUtils.cpp.s
.PHONY : math/MathUtils.cpp.s

math/Trigonometric.obj: math/Trigonometric.cpp.obj

.PHONY : math/Trigonometric.obj

# target to build an object file
math/Trigonometric.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/Trigonometric.cpp.obj
.PHONY : math/Trigonometric.cpp.obj

math/Trigonometric.i: math/Trigonometric.cpp.i

.PHONY : math/Trigonometric.i

# target to preprocess a source file
math/Trigonometric.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/Trigonometric.cpp.i
.PHONY : math/Trigonometric.cpp.i

math/Trigonometric.s: math/Trigonometric.cpp.s

.PHONY : math/Trigonometric.s

# target to generate assembly for a file
math/Trigonometric.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/math/Trigonometric.cpp.s
.PHONY : math/Trigonometric.cpp.s

tree/Trie.obj: tree/Trie.cpp.obj

.PHONY : tree/Trie.obj

# target to build an object file
tree/Trie.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/Trie.cpp.obj
.PHONY : tree/Trie.cpp.obj

tree/Trie.i: tree/Trie.cpp.i

.PHONY : tree/Trie.i

# target to preprocess a source file
tree/Trie.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/Trie.cpp.i
.PHONY : tree/Trie.cpp.i

tree/Trie.s: tree/Trie.cpp.s

.PHONY : tree/Trie.s

# target to generate assembly for a file
tree/Trie.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/Trie.cpp.s
.PHONY : tree/Trie.cpp.s

tree/UnionSet.obj: tree/UnionSet.cpp.obj

.PHONY : tree/UnionSet.obj

# target to build an object file
tree/UnionSet.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/UnionSet.cpp.obj
.PHONY : tree/UnionSet.cpp.obj

tree/UnionSet.i: tree/UnionSet.cpp.i

.PHONY : tree/UnionSet.i

# target to preprocess a source file
tree/UnionSet.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/UnionSet.cpp.i
.PHONY : tree/UnionSet.cpp.i

tree/UnionSet.s: tree/UnionSet.cpp.s

.PHONY : tree/UnionSet.s

# target to generate assembly for a file
tree/UnionSet.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/UnionSet.cpp.s
.PHONY : tree/UnionSet.cpp.s

tree/bit/BinaryIndexedTree.obj: tree/bit/BinaryIndexedTree.cpp.obj

.PHONY : tree/bit/BinaryIndexedTree.obj

# target to build an object file
tree/bit/BinaryIndexedTree.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/bit/BinaryIndexedTree.cpp.obj
.PHONY : tree/bit/BinaryIndexedTree.cpp.obj

tree/bit/BinaryIndexedTree.i: tree/bit/BinaryIndexedTree.cpp.i

.PHONY : tree/bit/BinaryIndexedTree.i

# target to preprocess a source file
tree/bit/BinaryIndexedTree.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/bit/BinaryIndexedTree.cpp.i
.PHONY : tree/bit/BinaryIndexedTree.cpp.i

tree/bit/BinaryIndexedTree.s: tree/bit/BinaryIndexedTree.cpp.s

.PHONY : tree/bit/BinaryIndexedTree.s

# target to generate assembly for a file
tree/bit/BinaryIndexedTree.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/bit/BinaryIndexedTree.cpp.s
.PHONY : tree/bit/BinaryIndexedTree.cpp.s

tree/heap/MaxHeap.obj: tree/heap/MaxHeap.cpp.obj

.PHONY : tree/heap/MaxHeap.obj

# target to build an object file
tree/heap/MaxHeap.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/heap/MaxHeap.cpp.obj
.PHONY : tree/heap/MaxHeap.cpp.obj

tree/heap/MaxHeap.i: tree/heap/MaxHeap.cpp.i

.PHONY : tree/heap/MaxHeap.i

# target to preprocess a source file
tree/heap/MaxHeap.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/heap/MaxHeap.cpp.i
.PHONY : tree/heap/MaxHeap.cpp.i

tree/heap/MaxHeap.s: tree/heap/MaxHeap.cpp.s

.PHONY : tree/heap/MaxHeap.s

# target to generate assembly for a file
tree/heap/MaxHeap.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/heap/MaxHeap.cpp.s
.PHONY : tree/heap/MaxHeap.cpp.s

tree/heap/MinHeap.obj: tree/heap/MinHeap.cpp.obj

.PHONY : tree/heap/MinHeap.obj

# target to build an object file
tree/heap/MinHeap.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/heap/MinHeap.cpp.obj
.PHONY : tree/heap/MinHeap.cpp.obj

tree/heap/MinHeap.i: tree/heap/MinHeap.cpp.i

.PHONY : tree/heap/MinHeap.i

# target to preprocess a source file
tree/heap/MinHeap.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/heap/MinHeap.cpp.i
.PHONY : tree/heap/MinHeap.cpp.i

tree/heap/MinHeap.s: tree/heap/MinHeap.cpp.s

.PHONY : tree/heap/MinHeap.s

# target to generate assembly for a file
tree/heap/MinHeap.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/tree/heap/MinHeap.cpp.s
.PHONY : tree/heap/MinHeap.cpp.s

util/SeqUtils.obj: util/SeqUtils.cpp.obj

.PHONY : util/SeqUtils.obj

# target to build an object file
util/SeqUtils.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/util/SeqUtils.cpp.obj
.PHONY : util/SeqUtils.cpp.obj

util/SeqUtils.i: util/SeqUtils.cpp.i

.PHONY : util/SeqUtils.i

# target to preprocess a source file
util/SeqUtils.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/util/SeqUtils.cpp.i
.PHONY : util/SeqUtils.cpp.i

util/SeqUtils.s: util/SeqUtils.cpp.s

.PHONY : util/SeqUtils.s

# target to generate assembly for a file
util/SeqUtils.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/util/SeqUtils.cpp.s
.PHONY : util/SeqUtils.cpp.s

util/Statistics.obj: util/Statistics.cpp.obj

.PHONY : util/Statistics.obj

# target to build an object file
util/Statistics.cpp.obj:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/util/Statistics.cpp.obj
.PHONY : util/Statistics.cpp.obj

util/Statistics.i: util/Statistics.cpp.i

.PHONY : util/Statistics.i

# target to preprocess a source file
util/Statistics.cpp.i:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/util/Statistics.cpp.i
.PHONY : util/Statistics.cpp.i

util/Statistics.s: util/Statistics.cpp.s

.PHONY : util/Statistics.s

# target to generate assembly for a file
util/Statistics.cpp.s:
	$(MAKE) -f CMakeFiles\jni.dir\build.make CMakeFiles/jni.dir/util/Statistics.cpp.s
.PHONY : util/Statistics.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... jni
	@echo ... rebuild_cache
	@echo ... global/bigint.obj
	@echo ... global/bigint.i
	@echo ... global/bigint.s
	@echo ... global/functions.obj
	@echo ... global/functions.i
	@echo ... global/functions.s
	@echo ... global/matrix.obj
	@echo ... global/matrix.i
	@echo ... global/matrix.s
	@echo ... global/trie.obj
	@echo ... global/trie.i
	@echo ... global/trie.s
	@echo ... graph/AdjacentMatrixGraph.obj
	@echo ... graph/AdjacentMatrixGraph.i
	@echo ... graph/AdjacentMatrixGraph.s
	@echo ... graph/FrontStarGraph.obj
	@echo ... graph/FrontStarGraph.i
	@echo ... graph/FrontStarGraph.s
	@echo ... math/BigInt.obj
	@echo ... math/BigInt.i
	@echo ... math/BigInt.s
	@echo ... math/MathUtils.obj
	@echo ... math/MathUtils.i
	@echo ... math/MathUtils.s
	@echo ... math/Trigonometric.obj
	@echo ... math/Trigonometric.i
	@echo ... math/Trigonometric.s
	@echo ... tree/Trie.obj
	@echo ... tree/Trie.i
	@echo ... tree/Trie.s
	@echo ... tree/UnionSet.obj
	@echo ... tree/UnionSet.i
	@echo ... tree/UnionSet.s
	@echo ... tree/bit/BinaryIndexedTree.obj
	@echo ... tree/bit/BinaryIndexedTree.i
	@echo ... tree/bit/BinaryIndexedTree.s
	@echo ... tree/heap/MaxHeap.obj
	@echo ... tree/heap/MaxHeap.i
	@echo ... tree/heap/MaxHeap.s
	@echo ... tree/heap/MinHeap.obj
	@echo ... tree/heap/MinHeap.i
	@echo ... tree/heap/MinHeap.s
	@echo ... util/SeqUtils.obj
	@echo ... util/SeqUtils.i
	@echo ... util/SeqUtils.s
	@echo ... util/Statistics.obj
	@echo ... util/Statistics.i
	@echo ... util/Statistics.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

