/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_algo4j_tree_seg_IntSegmentTree */

#ifndef _Included_org_algo4j_tree_seg_IntSegmentTree
#define _Included_org_algo4j_tree_seg_IntSegmentTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_algo4j_tree_seg_IntSegmentTree
 * Method:    set
 * Signature: (III[III)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_tree_seg_IntSegmentTree_set
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jint, jint);

/*
 * Class:     org_algo4j_tree_seg_IntSegmentTree
 * Method:    makeSeg
 * Signature: (I[I[II)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_tree_seg_IntSegmentTree_makeSeg
  (JNIEnv *, jobject, jint, jintArray, jintArray, jint);

/*
 * Class:     org_algo4j_tree_seg_IntSegmentTree
 * Method:    query
 * Signature: (III[II)I
 */
JNIEXPORT jint JNICALL Java_org_algo4j_tree_seg_IntSegmentTree_query
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
