/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_algo4j_tree_Trie */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"
#ifndef _Included_org_algo4j_tree_Trie
#define _Included_org_algo4j_tree_Trie

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_tree_Trie
 * Method:    createTrie
 * Signature: ()J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_tree_Trie_createTrie(
		JNIEnv *,
		jclass
) -> jlong;

/**
 * Class:     org_algo4j_tree_Trie
 * Method:    deleteTrie
 * Signature: (J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_tree_Trie_deleteTrie(
		JNIEnv *,
		jclass,
		jlong
) -> void;

/**
 * Class:     org_algo4j_tree_Trie
 * Method:    insert
 * Signature: (J[BLjava/lang/Object;)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_tree_Trie_set(
		JNIEnv *,
		jobject,
		jlong,
		jbyteArray,
		jobject
) -> void;

/**
 * Class:     org_algo4j_tree_Trie
 * Method:    remove
 * Signature: (J[B)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_tree_Trie_remove(
		JNIEnv *,
		jobject,
		jlong,
		jbyteArray
) -> void;

/**
 * Class:     org_algo4j_tree_Trie
 * Method:    contains
 * Signature: (J[B)Ljava/lang/Object;
 */
JNIEXPORT auto JNICALL Java_org_algo4j_tree_Trie_get(
		JNIEnv *,
		jobject,
		jlong,
		jbyteArray
) -> jobject;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_tree_Trie


#pragma clang diagnostic pop