/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_algo4j_tree_heap_Heap */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_tree_heap_MinHeap
#define _Included_org_algo4j_tree_heap_MinHeap

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_tree_heap_MinHeap
 * Method:    makeHeap
 * Signature: ([I)[I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_tree_heap_MinHeap_makeHeap(
		JNIEnv *,
		jclass,
		jintArray
) -> jintArray;

/**
 * Class:     org_algo4j_tree_heap_MinHeap
 * Method:    insert
 * Signature: ([III)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_tree_heap_MinHeap_insert(
		JNIEnv *,
		jclass,
		jintArray,
		jint,
		jint
) -> void;

/**
 * Class:     org_algo4j_tree_heap_MinHeap
 * Method:    minHeapify
 * Signature: ([III)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_tree_heap_MinHeap_minHeapify(
		JNIEnv *,
		jclass,
		jintArray,
		jint,
		jint
) -> void;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_tree_heap_MinHeap

#pragma clang diagnostic pop