/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_algo4j_util_MemoryHelper */

#ifndef _Included_org_algo4j_util_MemoryHelper
#define _Included_org_algo4j_util_MemoryHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_algo4j_util_MemoryHelper
 * Method:    allocateDoubles
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_algo4j_util_MemoryHelper_allocateDoubles
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_algo4j_util_MemoryHelper
 * Method:    fillDoubles
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_util_MemoryHelper_fillDoubles
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     org_algo4j_util_MemoryHelper
 * Method:    getDouble
 * Signature: (JI)J
 */
JNIEXPORT jdouble JNICALL Java_org_algo4j_util_MemoryHelper_getDouble
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_algo4j_util_MemoryHelper
 * Method:    setDouble
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_util_MemoryHelper_setDouble
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     org_algo4j_util_MemoryHelper
 * Method:    copyDoubles
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_util_MemoryHelper_copyDoubles
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_algo4j_util_MemoryHelper
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_util_MemoryHelper_free
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
