/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
/* Header for class org_algo4j_util_SeqUtils */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_util_SeqUtils
#define _Included_org_algo4j_util_SeqUtils

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    discretization
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_discretization___3JI (
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    discretization
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_discretization___3II (
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    discretization
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_discretization___3FI (
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    discretization
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_discretization___3DI (
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    inversion
 * Signature: ([II)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_inversion___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> jlong;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    inversion
 * Signature: ([JI)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_inversion___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> jlong;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    inversion
 * Signature: ([FI)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_inversion___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> jlong;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    inversion
 * Signature: ([DI)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_inversion___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> jlong;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortBubble
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortBubble___3II (
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortBubble
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortBubble___3JI (
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortBubble
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortBubble___3FI (
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortBubble
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortBubble___3DI (
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortQuick
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortQuick___3II (
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortQuick
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortQuick___3JI (
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortQuick
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortQuick___3FI (
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortQuick
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortQuick___3DI (
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortInsertion
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortInsertion___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortInsertion
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortInsertion___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortInsertion
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortInsertion___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortInsertion
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortInsertion___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortMerge
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortMerge___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortMerge
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortMerge___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortMerge
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortMerge___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortMerge
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortMerge___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortComb
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortComb___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortComb
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortComb___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortComb
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortComb___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortComb
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortComb___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortSelection
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortSelection___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortSelection
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortSelection___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortSelection
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortSelection___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortSelection
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortSelection___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortCocktail
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortCocktail___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortCocktail
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortCocktail___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortCocktail
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortCocktail___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortCocktail
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortCocktail___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;


#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_util_SeqUtils


#pragma clang diagnostic pop
