/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
/* Header for class org_ice1000_util_Arrays */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_ice1000_util_ArrayUtils
#define _Included_org_ice1000_util_ArrayUtils

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    discretization
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_discretization___3JI (
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    discretization
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_discretization___3II (
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    discretization
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_discretization___3FI (
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    discretization
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_discretization___3DI (
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortBubble
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortBubble___3II (
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortBubble
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortBubble___3JI (
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortBubble
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortBubble___3FI (
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortBubble
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortBubble___3DI (
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortQuick
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortQuick___3II (
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortQuick
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortQuick___3JI (
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortQuick
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortQuick___3FI (
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortQuick
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortQuick___3DI (
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortInsertion
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortInsertion___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortInsertion
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortInsertion___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortInsertion
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortInsertion___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortInsertion
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortInsertion___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortMerge
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortMerge___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortMerge
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortMerge___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortMerge
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortMerge___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortMerge
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortMerge___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortComb
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortComb___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortComb
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortComb___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortComb
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortComb___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortComb
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortComb___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortSelection
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortSelection___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortSelection
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortSelection___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortSelection
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortSelection___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortSelection
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortSelection___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortCocktail
 * Signature: ([II)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortCocktail___3II(
		JNIEnv *,
		jclass,
		jintArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortCocktail
 * Signature: ([JI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortCocktail___3JI(
		JNIEnv *,
		jclass,
		jlongArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortCocktail
 * Signature: ([FI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortCocktail___3FI(
		JNIEnv *,
		jclass,
		jfloatArray,
		jint
) -> void;

/**
 * Class:     org_ice1000_util_SequenceUtils
 * Method:    sortCocktail
 * Signature: ([DI)V
 */
JNIEXPORT auto JNICALL Java_org_ice1000_util_SequenceUtils_sortCocktail___3DI(
		JNIEnv *,
		jclass,
		jdoubleArray,
		jint
) -> void;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_ice1000_util_ArrayUtils


#pragma clang diagnostic pop
