/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
/* Header for class org_algo4j_util_SeqUtils */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_util_SeqUtils
#define _Included_org_algo4j_util_SeqUtils

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    discretization
 * Signature: ([J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_discretization___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    discretization
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_discretization___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    discretization
 * Signature: ([F)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_discretization___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    discretization
 * Signature: ([D)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_discretization___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    inversion
 * Signature: ([I)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_inversion___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> jlong;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    inversion
 * Signature: ([J)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_inversion___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> jlong;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    inversion
 * Signature: ([F)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_inversion___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> jlong;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    inversion
 * Signature: ([D)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_inversion___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> jlong;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortBubble
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortBubble___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortBubble
 * Signature: ([J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortBubble___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortBubble
 * Signature: ([F)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortBubble___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortBubble
 * Signature: ([D)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortBubble___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortQuick
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortQuick___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortQuick
 * Signature: ([J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortQuick___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortQuick
 * Signature: ([F)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortQuick___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortQuick
 * Signature: ([D)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortQuick___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortInsertion
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortInsertion___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortInsertion
 * Signature: ([J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortInsertion___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortInsertion
 * Signature: ([F)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortInsertion___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortInsertion
 * Signature: ([D)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortInsertion___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortMerge
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortMerge___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortMerge
 * Signature: ([J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortMerge___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortMerge
 * Signature: ([F)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortMerge___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortMerge
 * Signature: ([D)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortMerge___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortComb
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortComb___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortComb
 * Signature: ([J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortComb___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortComb
 * Signature: ([F)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortComb___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortComb
 * Signature: ([D)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortComb___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortSelection
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortSelection___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortSelection
 * Signature: ([J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortSelection___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortSelection
 * Signature: ([F)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortSelection___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortSelection
 * Signature: ([D)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortSelection___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortCocktail
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortCocktail___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortCocktail
 * Signature: ([J)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortCocktail___3J(
		JNIEnv *,
		jclass,
		jlongArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortCocktail
 * Signature: ([F)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortCocktail___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> void;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    sortCocktail
 * Signature: ([D)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_sortCocktail___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> void;


/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    copy
 * Signature: ([I)[I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_copy___3I(
		JNIEnv *,
		jclass,
		jintArray
) -> jintArray;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    copy
 * Signature: ([J)[J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_copy___3J(
	JNIEnv *,
	jclass,
	jlongArray
) -> jlongArray;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    copy
 * Signature: ([F)[F
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_copy___3F(
		JNIEnv *,
		jclass,
		jfloatArray
) -> jfloatArray;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    copy
 * Signature: ([D)[D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_copy___3D(
		JNIEnv *,
		jclass,
		jdoubleArray
) -> jdoubleArray;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    copy
 * Signature: ([S)[S
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_copy___3S(
		JNIEnv *,
		jclass,
		jshortArray
) -> jshortArray;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    copy
 * Signature: ([B)[B
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_copy___3B(
		JNIEnv *,
		jclass,
		jbyteArray
) -> jbyteArray;

/*
 * Class:     org_algo4j_util_SeqUtils
 * Method:    copy
 * Signature: ([Z)[Z
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_copy___3Z(
		JNIEnv *,
		jclass,
		jbooleanArray
) -> jbooleanArray;

/*
 * Class:     org_algo4j_util_SeqUtils
 * Method:    copy
 * Signature: ([C)[C
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_copy___3C(
		JNIEnv *,
		jclass,
		jcharArray
) -> jcharArray;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    kmp
 * Signature: ([I[I)I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_kmp___3I_3I(
		JNIEnv *,
		jclass,
		jintArray,
		jintArray
) -> jint;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    kmp
 * Signature: ([J[J)I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_kmp___3J_3J(
		JNIEnv *,
		jclass,
		jlongArray,
		jlongArray
) -> jint;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    kmp
 * Signature: ([C[C)I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_kmp___3C_3C(
		JNIEnv *,
		jclass,
		jcharArray,
		jcharArray
) -> jint;

/**
 * Class:     org_algo4j_util_SeqUtils
 * Method:    kmp
 * Signature: ([B[B)I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_util_SeqUtils_kmp___3B_3B(
		JNIEnv *,
		jclass,
		jbyteArray,
		jbyteArray
) -> jint;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_util_SeqUtils


#pragma clang diagnostic pop
