/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
#include <jni.h>
/* Header for class org_algo4j_graph_AdjacentMatrix */

#ifndef _Included_org_algo4j_graph_AdjacentMatrix
#define _Included_org_algo4j_graph_AdjacentMatrix

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

#undef org_algo4j_graph_AdjacentMatrix_ORIGINAL_FILLING_VALUE
#define org_algo4j_graph_AdjacentMatrix_ORIGINAL_FILLING_VALUE 2147483647L

/**
 * Class:     org_algo4j_graph_AdjacentMatrix
 * Method:    floyd
 * Signature: ([I)[I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_graph_AdjacentMatrix_floyd(
		JNIEnv *,
		jclass,
		jintArray
) -> jintArray;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_graph_AdjacentMatrix

