/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
#include "jni.h"
/* Header for class org_algo4j_graph_AdjacentMatrixGraph */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"
#ifndef _Included_org_algo4j_graph_AdjacentMatrixGraph
#define _Included_org_algo4j_graph_AdjacentMatrixGraph

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

#undef AdjacentMatrixGraph_ORIGINAL_FILLING_VALUE
#define AdjacentMatrixGraph_ORIGINAL_FILLING_VALUE 2147483647L

/**
 * Class:     org_algo4j_graph_AdjacentMatrixGraph
 * Method:    floyd
 * Signature: ([I)[I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_graph_AdjacentMatrixGraph_floyd(
		JNIEnv *,
		jclass,
		jintArray
) -> jintArray;

/**
 * Class:     org_algo4j_graph_AdjacentMatrixGraph
 * Method:    dijkstra
 * Signature: (I[I)[I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_graph_AdjacentMatrixGraph_dijkstra(
		JNIEnv *env,
		jclass,
		jint,
		jintArray
) -> jintArray;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_graph_AdjacentMatrixGraph


#pragma clang diagnostic pop