/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
/* Header for class org_algo4j_graph_FrontStarGraph */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_graph_FrontStarGraph
#define _Included_org_algo4j_graph_FrontStarGraph

#undef org_algo4j_graph_FrontStarGraph_INFINITY
#define org_algo4j_graph_FrontStarGraph_INFINITY 2139062143L

#undef org_algo4j_graph_FrontStarGraph_INFINITY_FILLING
#define org_algo4j_graph_FrontStarGraph_INFINITY_FILLING 127L

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_graph_FrontStarGraph
 * Method:    spfa
 * Signature: ()[J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_graph_FrontStarGraph_spfa(
		JNIEnv *,
		jobject,
		jint,
		jlongArray,
		jlongArray,
		jlongArray,
		jlongArray,
		jint,
		jint
) -> jlongArray;

/**
 * Class:     org_algo4j_graph_FrontStarGraph
 * Method:    kruskal
 * Signature: ([J[J[J[J[JII)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_graph_FrontStarGraph_kruskal(
		JNIEnv *,
		jobject,
		jlongArray,
		jlongArray,
		jlongArray,
		jlongArray,
		jlongArray,
		jint,
		jint
) -> jlong;

typedef struct FrontStarNode {
	jint value;
	jint to;
	jint from;

	FrontStarNode(const jint v, const jint t, const jint f) : value(v), to(t), from(f) {  }
	FrontStarNode() {  }
	~FrontStarNode() {  }

	/**
	 * set values of fields
	 */
	void setValue(const jint v, const jint t, const jint f) {
		value = v;
		from = f;
		to = t;
	}

	const bool operator<(const FrontStarNode &o) const {
		return value < o.value;
	}

	const bool operator==(const FrontStarNode &o) const {
		return value == o.value;
	}
} FrontStarNode;

#ifdef __cplusplus
}
#endif /// __cplusplus
#endif /// org_algo4j_graph_FrontStarGraph

#pragma clang diagnostic pop