/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_algo4j_linear_Heap */

#ifndef _Included_org_algo4j_linear_Heap
#define _Included_org_algo4j_linear_Heap

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_graph_Heap
 * Method:    makeHeap
 * Signature: ([I)[I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_graph_Heap_makeHeap(
		JNIEnv *,
		jclass,
		jintArray
) -> jintArray;

/**
 * Class:     org_algo4j_graph_Heap
 * Method:    insert
 * Signature: ([I)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_graph_Heap_insert(
		JNIEnv *,
		jclass,
		jintArray,
		jint,
		jint
) -> void;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_linear_Heap
