/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
/* Header for class org_algo4j_graph_UnionSet */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_graph_UnionSet
#define _Included_org_algo4j_graph_UnionSet

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_graph_UnionSet
 * Method:    find
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_org_algo4j_graph_UnionSet_find(
		JNIEnv *,
		jobject,
		jintArray,
		jint
);

/**
 * Class:     org_algo4j_graph_UnionSet
 * Method:    merge
 * Signature: ([IIII)V
 */
// JNIEXPORT void JNICALL Java_org_algo4j_graph_UnionSet_merge(
// 		JNIEnv *,
// 		jobject,
// 		jintArray,
// 		jint,
// 		jint,
// 		jint
// );

#ifdef __cplusplus
}
#endif /// __cplusplus
#endif

#pragma clang diagnostic pop
