/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ice1000_math_Matrix */

#ifndef _Included_org_ice1000_math_Matrix
#define _Included_org_ice1000_math_Matrix

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_ice1000_math_Matrix
 * Method:    sum
 * Signature: ([JII)I
 */
JNIEXPORT jint JNICALL Java_org_ice1000_math_Matrix_sum(
		JNIEnv *,
		jobject,
		jlongArray,
		jint,
		jint
);

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_ice1000_math_Matrix

