/** DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
/** Header for class org_algo4j_util_MathUtils */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_math_MathUtils
#define _Included_org_algo4j_math_MathUtils

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/// 0x5F3759DF thank you Carmack
#undef org_algo4j_math_MathUtils_MAGIC_NUMBER
#define org_algo4j_math_MathUtils_MAGIC_NUMBER 1597463007L

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    gcd
 * Signature: (JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_gcd(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    exgcd
 * Signature: ([JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_exgcdJni(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlongArray;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    gcdStein
 * Signature: (JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_gcdStein(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    sqrtCarmark
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_sqrtCarmark(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_sqrt(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    fastPlus
 * Signature: (JJJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_fastPlus(
		JNIEnv *,
		jclass,
		jlong,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    fastPower
 * Signature: (JJJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_fastPower(
		JNIEnv *,
		jclass,
		jlong,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    abs
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_abs__D(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    abs
 * Signature: (F)F
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_abs__F(
		JNIEnv *,
		jclass,
		jfloat
) -> jfloat;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    abs
 * Signature: (I)I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_abs__I(
		JNIEnv *,
		jclass,
		jint
) -> jint;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    abs
 * Signature: (J)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_abs__J(
		JNIEnv *,
		jclass,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    max
 * Signature: (JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_max__JJ(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:		max
 * Signature: (II)I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_max__II(
		JNIEnv *,
		jclass,
		jint,
		jint
) -> jint;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    max
 * Signature: (FF)F
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_max__FF(
		JNIEnv *,
		jclass,
		jfloat,
		jfloat
) -> jfloat;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    max
 * Signature: (DD)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_max__DD(
		JNIEnv *,
		jclass,
		jdouble,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    min
 * Signature: (II)I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_min__II(
		JNIEnv *,
		jclass,
		jint,
		jint
) -> jint;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    min
 * Signature: (JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_min__JJ(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    min
 * Signature: (FF)F
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_min__FF(
		JNIEnv *,
		jclass,
		jfloat,
		jfloat
) -> jfloat;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    min
 * Signature: (DD)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_min__DD(
		JNIEnv *,
		jclass,
		jdouble,
		jdouble
) -> jdouble;


/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    ln
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_ln(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    lg
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_lg(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    isPrime
 * Signature: (J)Z
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_isPrime(
		JNIEnv *,
		jclass,
		jlong
) -> jboolean;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    fib
 * Signature: (JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_fib(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlong;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_math_MathUtils

#pragma clang diagnostic pop
