/** DO NOT EDIT THIS FILE - it is machine generated */
#include "../global/functions.h"
/** Header for class org_algo4j_util_MathUtils */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_math_MathUtils
#define _Included_org_algo4j_math_MathUtils

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/// 0x5F3759DF thank you Carmack
#undef org_algo4j_math_MathUtils_MAGIC_NUMBER
#define org_algo4j_math_MathUtils_MAGIC_NUMBER 1597463007L

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    gcd
 * Signature: (JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_gcd(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    exgcd
 * Signature: ([JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_exgcdJni(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlongArray;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    gcdStein
 * Signature: (JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_gcdStein(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    sqrtCarmark
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_sqrtCarmark(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_sqrt(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    fastMul
 * Signature: (JJJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_fastMul(
		JNIEnv *,
		jclass,
		jlong,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    fastPlus
 * Signature: (JJJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_fastPlus(
		JNIEnv *,
		jclass,
		jlong,
		jlong,
		jlong
) -> jlong;
/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    fastPlus
 * Signature: (JJJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_fastPlus(
		JNIEnv *,
		jclass,
		jlong,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    fastPower
 * Signature: (JJJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_fastPower(
		JNIEnv *,
		jclass,
		jlong,
		jlong,
		jlong
) -> jlong;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    ln
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_ln(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    lg
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_lg(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    isPrime
 * Signature: (J)Z
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_isPrime(
		JNIEnv *,
		jclass,
		jlong
) -> jboolean;

/**
 * Class:     org_algo4j_math_MathUtils
 * Method:    fib
 * Signature: (JJ)J
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_MathUtils_fib(
		JNIEnv *,
		jclass,
		jlong,
		jlong
) -> jlong;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_math_MathUtils

#pragma clang diagnostic pop
