/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include <math.h>
#include "../global/functions.h"
/* Header for class org_algo4j_math_Trigonometric */

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_math_Trigonometric
#define _Included_org_algo4j_math_Trigonometric

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_math_Trigonometric
 * Method:    sin
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_Trigonometric_sin(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;


/**
 * Class:     org_algo4j_math_Trigonometric
 * Method:    cos
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_Trigonometric_cos(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_Trigonometric
 * Method:    tan
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_Trigonometric_tan(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_Trigonometric
 * Method:    cot
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_Trigonometric_cot(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_Trigonometric
 * Method:    csc
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_Trigonometric_csc(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

/**
 * Class:     org_algo4j_math_Trigonometric
 * Method:    sec
 * Signature: (D)D
 */
JNIEXPORT auto JNICALL Java_org_algo4j_math_Trigonometric_sec(
		JNIEnv *,
		jclass,
		jdouble
) -> jdouble;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_math_Trigonometric


#pragma clang diagnostic pop
