/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_algo4j_math_Vector */

#ifndef _Included_org_algo4j_math_Vector
#define _Included_org_algo4j_math_Vector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_algo4j_math_Vector
 * Method:    add
 * Signature: (JDI)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_math_Vector_add__JDI
        (JNIEnv *, jobject, jlong, jdouble, jint);

/*
 * Class:     org_algo4j_math_Vector
 * Method:    add
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_math_Vector_add__JJI
        (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_algo4j_math_Vector
 * Method:    multiply
 * Signature: (JDI)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_math_Vector_multiply__JDI
        (JNIEnv *, jobject, jlong, jdouble, jint);

/*
 * Class:     org_algo4j_math_Vector
 * Method:    multiply
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_algo4j_math_Vector_multiply__JJI
        (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_algo4j_math_Vector
 * Method:    product
 * Signature: (JJI)D
 */
JNIEXPORT jdouble JNICALL Java_org_algo4j_math_Vector_product
        (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
