/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "../global/functions.h"

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_win_WinAPI
#define _Included_org_algo4j_win_WinAPI

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_win_WinAPI
 * Method:    beep
 * Signature: (II)Z
 */
JNIEXPORT auto JNICALL Java_org_algo4j_win_WinAPI_beep(
		JNIEnv *,
		jclass,
		jint,
		jint
) -> jboolean;

/**
 * Class:     org_algo4j_win_WinAPI
 * Method:    messageBox
 * Signature: ([B[BI)I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_win_WinAPI_messageBoxA(
		JNIEnv *,
		jclass,
		jbyteArray,
		jbyteArray,
		jint
) -> jint;

/**
 * Class:     org_algo4j_win_WinAPI
 * Method:    getPowerStatus
 * Signature: ()[I
 */
JNIEXPORT auto JNICALL Java_org_algo4j_win_WinAPI_getPowerStatus(
		JNIEnv *,
		jclass
) -> jintArray;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_win_WinAPI


#pragma clang diagnostic pop
