/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "../global/functions.h"
#include "../global/winapi.h"

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"

#ifndef _Included_org_algo4j_win_WinAPI
#define _Included_org_algo4j_win_WinAPI

#ifdef __cplusplus
extern "C" {
#endif /// __cplusplus

/**
 * Class:     org_algo4j_win_WinAPI
 * Method:    beep
 * Signature: (II)V
 */
JNIEXPORT auto JNICALL Java_org_algo4j_win_WinAPI_beep(
		JNIEnv *,
		jclass,
		jint,
		jint
) -> void;

#ifdef __cplusplus
}
#endif /// __cplusplus

#endif /// _Included_org_algo4j_win_WinAPI


#pragma clang diagnostic pop
